source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'bcrypt'
gem 'bootsnap', require: false
# Use Active Storage variant
# gem 'image_processing'
gem 'jbuilder'
gem 'pg'
gem 'puma'
gem 'rails', '>= 6.1.3.2'
gem 'redis-rails', '>= 5.0.2'
gem 'sass-rails', '>= 6.0.0'
gem 'sidekiq'
gem 'turbolinks'
gem 'unicorn'
gem 'webpacker', '>= 5.2.1'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
